#服务的端口，可在启动时动态配置
server:
  port: 8762
#服务要注册的地址  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
#defaultZone: http://peer1:8761/eureka/集群的配置，向一个节点注册，其余节点也可以读取到     

#服务的应用名称
spring:
  application:
    name: service-hi
#  zipkin:
#    base-url: http://localhost:9062
