#服务的应用名称
spring:
  profiles: service-hi
  application:
    name: service-hi
#服务的端口，可在启动时动态配置
server:
  port: 8762
#服务要注册的地址  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

#服务的应用名称
spring:
  profiles: service-lucy
  application:
    name: service-lucy
#服务的端口，可在启动时动态配置
server:
  port: 8763
#服务要注册的地址  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/